### ISSUE TITLE
关于论文中Table1的数据疑惑

### ISSUE THREAD

**Issue by frreason** [Srameo/LED#2]
您好，我想问一个问题，关于您论文ELD和SID方法的一些测试数据，好像和ELD论文里及PMN论文里的测试数据对不上？还是说您测试的方法不一致？
比如ELD期刊版本的论文里，paired data训练的结果在ELD的SonyA7S2子集上是大概42.45（x200），ELD建模方法是43.42（x200）。但是我看您的论文里的数据（Table 1）ELD是42.544（x200）。以及在SID的Sony子集上数据好像也对不上。

**Comment by Srameo** [comment]
Hi there, thanks for the question on the evluation metrics of Tab.1 and Tab.2 of the our main paper.

1. For the metrics on the SID Sony subset, 
    1. **Metrics in ELD:** ELD performed center crop during testing, please refer to the official code of ELD ([official repo](https://github.com/Vandermode/ELD/blob/master/test_SID.py#L45)). This is due to that the dark shading (a kind of out-of-model noise for the ELD noise model) in SID Sony subset, thus ELD performed center crop during testing for better performance. 
    2. **Metrics in PMN:** Their training strategy is not the same as the training strategy in Tab.1, thus resulting in different performance. We have already provided a ELD model training with exactly the same strategy as PMN in Tab.4 of the main paper for fair comparsion. In our implementation, ELD (in Tab.4) outperforms the reproduced ELD model in PMN. 
2. For the metrics on the ELD Sony subset, due to that LED requires fine-tuning using few-shot pairs of the target camera, we use scene-1/2 of the ELD dataset for fine-tuning, and other scenes for testing. For other methods, we only test them on the scenes except scene-1/2 for fair comparison, thus resulting in different metrics.

Besides, it's worth noting that the main contribution of LED is **fast adaptation** to new cameras with fewer data collection and fewer training cost with better performance.

--------------------------------
您好！感谢您对我们表1以及表2中的指标提出质疑！

1. 对于 SID Sony 子集上的指标，
    1. **与ELD中的指标相比**：ELD在测试时只用了中心的512x512的区域，具体请参考ELD[官方代码](https://github.com/Vandermode/ELD/blob/master/test_SID.py#L45)。这是由于在SID Sony子集上存在 Dark Shading （对于ELD的噪声模型来讲，是一种模型外噪声），因此ELD在测试时进行了中心裁剪以获得更好的性能。
    2. **与PMN中的指标相比**：我们在表1中使用的训练策略与PMN不同，这是导致ELD指标下降的原因。当然，我们也提供使用与PMN相同训练策略的ELD模型，可以在表4中找到。在我们的实现中，ELD（表4）比PMN中复现的ELD指标要更高。
2. 对于 ELD Sony 子集上的指标，由于LED的流程中需要使用目标相机的少量配对数据进行微调，因此我们使用ELD中的场景1/2进行了微调，其余场景用于测试。对于其他方法我们只使用了其他场景（除了场景1/2）的数据进行了测试以便于公平对比，这是出现指标不同的原因。

此外，值得注意的是，LED的贡献是可以**快速部署**到新相机上，并且仅需少量数据和训练时间以获得更好的性能。

**Comment by frreason** [comment]
好的明白啦，很感谢您的回答！
